# create environment : conda env create -f environment.yml
name: calval_disp
channels:
  - conda-forge
dependencies:
  - asf_search
  - awscli
  - cartopy
  - deepdiff
  - dem_stitcher>=2.5.8
  - gdal>=3.4.1
  - geopandas
  - git-lfs
  - h5py
  - joblib
  - jupyter_contrib_nbextensions
  - jupyterlab
  - matplotlib
  - nbdime
  - netcdf4
  - numpy
  - pandas
  - papermill
  - pillow
  - pip
  - pypdf2
  - pyproj
  - pyresample
  - pymupdf
  - rasterio
  - requests
  - rioxarray
  - ruptures
  - scipy>1.10.0
  - seaborn
  - shapely
  - s3fs
  - utm
  - wget
  - wkhtmltopdf
  - xarray
  # Pip dependencies
  - pip:
    - hectorp
    - imgkit
    - pdfkit
    - Wand
